const PID_CATALOG = {
  "04": { name: "engineLoadPct", unit: "%", bytes: 1 },
  "05": { name: "coolantTempC", unit: "C", bytes: 1 },
  "06": { name: "shortTermFuelTrimBank1Pct", unit: "%", bytes: 1 },
  "07": { name: "longTermFuelTrimBank1Pct", unit: "%", bytes: 1 },
  "08": { name: "shortTermFuelTrimBank2Pct", unit: "%", bytes: 1 },
  "09": { name: "longTermFuelTrimBank2Pct", unit: "%", bytes: 1 },
  "0A": { name: "fuelPressureKpa", unit: "kPa", bytes: 1 },
  "0B": { name: "mapKpa", unit: "kPa", bytes: 1 },
  "0C": { name: "rpm", unit: "rpm", bytes: 2 },
  "0D": { name: "speedKph", unit: "kph", bytes: 1 },
  "0E": { name: "ignitionTimingAdvanceDeg", unit: "deg", bytes: 1 },
  "0F": { name: "intakeAirTempC", unit: "C", bytes: 1 },
  "10": { name: "mafGramsPerSec", unit: "g/s", bytes: 2 },
  "11": { name: "throttlePosPct", unit: "%", bytes: 1 },
  "14": { name: "o2B1S1VoltageV", unit: "V", bytes: 2 },
  "15": { name: "o2B1S2VoltageV", unit: "V", bytes: 2 },
  "18": { name: "o2B2S1VoltageV", unit: "V", bytes: 2 },
  "19": { name: "o2B2S2VoltageV", unit: "V", bytes: 2 },
  "1F": { name: "engineRunTimeSec", unit: "s", bytes: 2 },
  "21": { name: "distanceWithMilOnKm", unit: "km", bytes: 2 },
  "22": { name: "fuelRailPressureRelativeKpa", unit: "kPa", bytes: 2 },
  "23": { name: "fuelRailGaugePressureKpa", unit: "kPa", bytes: 2 },
  "2C": { name: "commandedEgrPct", unit: "%", bytes: 1 },
  "2D": { name: "egrErrorPct", unit: "%", bytes: 1 },
  "2E": { name: "commandedEvapPurgePct", unit: "%", bytes: 1 },
  "2F": { name: "fuelLevelPct", unit: "%", bytes: 1 },
  "30": { name: "warmupsSinceClear", unit: "count", bytes: 1 },
  "31": { name: "distanceSinceClearKm", unit: "km", bytes: 2 },
  "32": { name: "evapSystemVaporPressurePa", unit: "Pa", bytes: 2 },
  "33": { name: "barometricPressureKpa", unit: "kPa", bytes: 1 },
  "3C": { name: "catalystTempB1S1C", unit: "C", bytes: 2 },
  "3D": { name: "catalystTempB2S1C", unit: "C", bytes: 2 },
  "3E": { name: "catalystTempB1S2C", unit: "C", bytes: 2 },
  "3F": { name: "catalystTempB2S2C", unit: "C", bytes: 2 },
  "42": { name: "batteryVoltageV", unit: "V", bytes: 2 },
  "43": { name: "absoluteLoadPct", unit: "%", bytes: 2 },
  "44": { name: "commandedEquivalenceRatio", unit: "lambda", bytes: 2 },
  "45": { name: "relativeThrottlePosPct", unit: "%", bytes: 1 },
  "46": { name: "ambientTempC", unit: "C", bytes: 1 },
  "47": { name: "absoluteThrottleBPosPct", unit: "%", bytes: 1 },
  "48": { name: "absoluteThrottleCPosPct", unit: "%", bytes: 1 },
  "49": { name: "acceleratorPedalDPosPct", unit: "%", bytes: 1 },
  "4A": { name: "acceleratorPedalEPosPct", unit: "%", bytes: 1 },
  "4B": { name: "acceleratorPedalFPosPct", unit: "%", bytes: 1 },
  "4C": { name: "commandedThrottleActuatorPct", unit: "%", bytes: 1 },
  "4D": { name: "milRunTimeMin", unit: "min", bytes: 2 },
  "4E": { name: "timeSinceClearMin", unit: "min", bytes: 2 },
  "52": { name: "ethanolFuelPct", unit: "%", bytes: 1 },
  "53": { name: "absoluteEvapVaporPressureKpa", unit: "kPa", bytes: 2 },
  "54": { name: "evapSystemVaporPressureWidePa", unit: "Pa", bytes: 2 },
  "59": { name: "fuelRailAbsolutePressureKpa", unit: "kPa", bytes: 2 },
  "5A": { name: "relativeAcceleratorPedalPct", unit: "%", bytes: 1 },
  "5B": { name: "hybridBatteryRemainingPct", unit: "%", bytes: 1 },
  "5C": { name: "oilTempC", unit: "C", bytes: 1 },
  "5D": { name: "fuelInjectionTimingDeg", unit: "deg", bytes: 2 },
  "5E": { name: "fuelRateLph", unit: "L/h", bytes: 2 },
  "61": { name: "driverDemandTorquePct", unit: "%", bytes: 1 },
  "62": { name: "actualTorquePct", unit: "%", bytes: 1 },
  "63": { name: "referenceTorqueNm", unit: "Nm", bytes: 2 },
  "A6": { name: "odometerKm", unit: "km", bytes: 4 }
};

module.exports = {
  PID_CATALOG
};
