"use strict";

const EVENT_TYPE = Object.freeze({
  DUTY_STATUS: 1,
  INTERMEDIATE_LOG: 2,
  SPECIAL_DRIVING: 3,
  CERTIFICATION: 4,
  LOGIN_LOGOUT: 5,
  ENGINE_POWER: 6,
  MALFUNCTION_DIAGNOSTIC: 7
});

const DUTY_CODE = Object.freeze({
  OFF_DUTY: 1,
  SLEEPER: 2,
  DRIVING: 3,
  ON_DUTY: 4
});

const DUTY_NAME_BY_CODE = Object.freeze(Object.fromEntries(
  Object.entries(DUTY_CODE).map(([name, code]) => [code, name])
));

const RECORD_ORIGIN = Object.freeze({
  AUTOMATIC: 1,
  DRIVER: 2,
  CARRIER_EDIT: 3,
  UNIDENTIFIED: 4
});

const RECORD_STATUS = Object.freeze({
  ACTIVE: 1,
  INACTIVE_CHANGED: 2,
  INACTIVE_CHANGE_REQUESTED: 3,
  INACTIVE_CHANGE_REJECTED: 4
});

const SPECIAL_DRIVING_CODE = Object.freeze({
  CLEARED: 0,
  PERSONAL_CONVEYANCE: 1,
  YARD_MOVE: 2
});

const LOGIN_CODE = Object.freeze({ LOGIN: 1, LOGOUT: 2 });
const ENGINE_POWER_CODE = Object.freeze({
  POWER_UP_CONVENTIONAL: 1,
  SHUT_DOWN_CONVENTIONAL: 2,
  POWER_UP_REDUCED: 3,
  SHUT_DOWN_REDUCED: 4
});

const DIAGNOSTIC_CODE = Object.freeze({
  POWER: "P",
  ENGINE_SYNC: "E",
  TIMING: "T",
  POSITIONING: "L",
  DATA_RECORDING: "R",
  DATA_TRANSFER: "S",
  UNIDENTIFIED_DRIVING: "O"
});

const DIAGNOSTIC_EVENT_CODE = Object.freeze({
  MALFUNCTION_DETECTED: 1,
  MALFUNCTION_CLEARED: 2,
  DIAGNOSTIC_DETECTED: 3,
  DIAGNOSTIC_CLEARED: 4
});

const VALID_MULTIDAY_BASES = new Set(["US_60_7", "US_70_8"]);
const VEHICLE_MOVING_KPH = 8.04672; // 5 mph, Appendix A section 4.3.1.2.
const AUTO_ON_DUTY_AFTER_STOP_MS = 6 * 60 * 1000;
const INTERMEDIATE_LOG_INTERVAL_MS = 60 * 60 * 1000;

module.exports = {
  EVENT_TYPE,
  DUTY_CODE,
  DUTY_NAME_BY_CODE,
  RECORD_ORIGIN,
  RECORD_STATUS,
  SPECIAL_DRIVING_CODE,
  LOGIN_CODE,
  ENGINE_POWER_CODE,
  DIAGNOSTIC_CODE,
  DIAGNOSTIC_EVENT_CODE,
  VALID_MULTIDAY_BASES,
  VEHICLE_MOVING_KPH,
  AUTO_ON_DUTY_AFTER_STOP_MS,
  INTERMEDIATE_LOG_INTERVAL_MS
};
