store = {
    "companies": {},
    "vehicles": {},
    "devices": {},
    "pairing_codes": {},
    "telemetry_latest": {},
    "telemetry_history": {},
    "telemetry_latest_normalized": {},
    "telemetry_history_normalized": {},
    "vehicle_activation": {},
    "baseline_models": {},
    "baseline_flags": {},
    "alerts": {},
    "alert_counter": 0,
    "ai_cooldowns": {},
    "insights_latest": {},
    "driver_devices": {},
    "driver_trips": {},
    "driver_telemetry": {},
    "driver_alerts": {},
}
